-- ============================================================
-- seed.sql — dati iniziali (generato dai dati dell'app)
-- Eseguire DOPO schema.sql. Idempotente: usa upsert su slug/key.
-- ============================================================

-- Micronutrienti
insert into public.micronutrients (key, name, "function") values ('vitamina_c', 'Vitamina C', 'Contribuisce alla normale funzione del sistema immunitario, alla sintesi del collagene e alla protezione delle cellule dallo stress ossidativo.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";
insert into public.micronutrients (key, name, "function") values ('vitamina_a', 'Vitamina A / Beta-carotene', 'Il beta-carotene è precursore della vitamina A, importante per la normale funzione visiva, per la pelle e per il sistema immunitario.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";
insert into public.micronutrients (key, name, "function") values ('vitamina_k', 'Vitamina K', 'Contribuisce alla normale coagulazione del sangue e al mantenimento di ossa normali.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";
insert into public.micronutrients (key, name, "function") values ('folati', 'Folati (Vitamina B9)', 'Contribuiscono alla normale sintesi degli amminoacidi e alla normale formazione del sangue; utili nei periodi di crescita dei tessuti.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";
insert into public.micronutrients (key, name, "function") values ('vitamina_b6', 'Vitamina B6', 'Contribuisce al normale metabolismo energetico e alla normale funzione del sistema nervoso.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";
insert into public.micronutrients (key, name, "function") values ('potassio', 'Potassio', 'Contribuisce alla normale funzione muscolare, alla funzione del sistema nervoso e al mantenimento di una pressione sanguigna normale.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";
insert into public.micronutrients (key, name, "function") values ('magnesio', 'Magnesio', 'Contribuisce al normale metabolismo energetico, alla funzione muscolare e alla riduzione di stanchezza e affaticamento.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";
insert into public.micronutrients (key, name, "function") values ('manganese', 'Manganese', 'Contribuisce alla normale formazione del tessuto connettivo e alla protezione delle cellule dallo stress ossidativo.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";
insert into public.micronutrients (key, name, "function") values ('polifenoli', 'Polifenoli', 'Ampia famiglia di composti vegetali con documentata attività antiossidante in vitro; contribuiscono al colore e al sapore di frutta e verdura.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";
insert into public.micronutrients (key, name, "function") values ('antociani', 'Antociani', 'Pigmenti vegetali della famiglia dei polifenoli, responsabili delle tonalità rosse, viola e blu, con attività antiossidante.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";
insert into public.micronutrients (key, name, "function") values ('flavonoidi', 'Flavonoidi', 'Sottogruppo dei polifenoli diffuso in agrumi e frutti; contribuiscono alle proprietà antiossidanti dell''alimento.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";
insert into public.micronutrients (key, name, "function") values ('licopene', 'Licopene', 'Carotenoide di colore rosso presente soprattutto nel pomodoro e nell''anguria, con attività antiossidante.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";
insert into public.micronutrients (key, name, "function") values ('betalaine', 'Betalaine', 'Pigmenti rosso-porpora tipici della barbabietola, con attività antiossidante studiata in vitro.')
  on conflict (key) do update set name=excluded.name, "function"=excluded."function";

-- Ingredienti
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('mela', 'Mela', 'frutta', '#8FBF5A', '🍎', 0.65, 'Apporta zuccheri naturalmente presenti, potassio e diversi composti polifenolici. Base dolce e versatile.', 'Lavare bene, rimuovere il torsolo. Non serve sbucciare se la buccia è integra.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('pera', 'Pera', 'frutta', '#C7D48A', '🍐', 0.6, 'Dolcezza morbida, fibra solubile e potassio. Rende il succo vellutato.', 'Usare pere mature ma sode. Rimuovere il torsolo; buccia lavata ammessa.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('pesca', 'Pesca', 'frutta', '#F4B183', '🍑', 0.55, 'Zuccheri, beta-carotene e vitamina C. Aroma estivo e delicato.', 'Rimuovere il nocciolo. Preferire pesche mature per una resa migliore.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('nettarina', 'Nettarina', 'frutta', '#F0A57C', '🍑', 0.55, 'Simile alla pesca: zuccheri, carotenoidi e vitamina C, con buccia liscia.', 'Rimuovere il nocciolo. La buccia liscia può essere lasciata dopo lavaggio.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('prugna', 'Prugna', 'frutta', '#8E5B8E', '🫐', 0.5, 'Zuccheri, sorbitolo e polifenoli. Colore intenso e sapore pieno.', 'Rimuovere il nocciolo. Alternare con ingredienti più sodi per estrarre bene.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('uva', 'Uva', 'frutta', '#7E57C2', '🍇', 0.7, 'Zuccheri prontamente disponibili, potassio e polifenoli (soprattutto uva nera).', 'Staccare gli acini dal grappolo. Ottima resa; molto dolce, dosare con equilibrio.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('arancia', 'Arancia', 'frutta', '#F59E42', '🍊', 0.5, 'Fonte di vitamina C, folati e flavonoidi. Freschezza agrumata.', 'Sbucciare rimuovendo la parte bianca amara. Non centrifugare la scorza.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('mandarino', 'Mandarino', 'frutta', '#F2933C', '🍊', 0.45, 'Vitamina C e flavonoidi, con dolcezza più marcata dell''arancia.', 'Sbucciare ed eliminare eventuali semi. Non usare la scorza.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('pompelmo', 'Pompelmo', 'frutta', '#EF7E82', '🍊', 0.5, 'Vitamina C, flavonoidi e note amare-acidule che bilanciano i succhi dolci.', 'Sbucciare rimuovendo albedo e membrane. Attenzione a possibili interazioni con farmaci.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('limone', 'Limone', 'frutta', '#F4D35E', '🍋', 0.45, 'Fonte di vitamina C e acido citrico. Ravviva e bilancia la dolcezza.', 'Sbucciare la scorza esterna. Bastano piccole quantità per l''aroma.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('lime', 'Lime', 'frutta', '#B5D33D', '🍋', 0.4, 'Acido citrico e vitamina C, con aroma più intenso e verde del limone.', 'Sbucciare la scorza. Usare in piccole dosi per non coprire gli altri sapori.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('ananas', 'Ananas', 'frutta', '#F2C94C', '🍍', 0.55, 'Zuccheri, vitamina C e manganese. Sapore tropicale e leggermente acidulo.', 'Eliminare buccia e parte centrale più fibrosa. Molto succoso.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('anguria', 'Anguria', 'frutta', '#F76C6C', '🍉', 0.72, 'Molto idratante, apporta licopene e potassio con poche calorie.', 'Rimuovere la buccia. Resa altissima; il succo è molto liquido e dolce.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('melone', 'Melone', 'frutta', '#F6B26B', '🍈', 0.6, 'Beta-carotene, vitamina C e potassio. Dolcezza aromatica e idratante.', 'Rimuovere buccia e semi. Preferire melone maturo e profumato.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('kiwi', 'Kiwi', 'frutta', '#7CB342', '🥝', 0.55, 'Elevato contenuto di vitamina C, con potassio e polifenoli.', 'Sbucciare. Non eccedere: i piccoli semi possono dare una nota leggermente amara.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('melograno', 'Melograno', 'frutta', '#C0392B', '🔴', 0.45, 'Ricco di polifenoli e antociani, con vitamina C e sapore agrodolce.', 'Usare solo i chicchi (arilli). Colora intensamente; macchia i tessuti.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('mirtilli', 'Mirtilli', 'frutti-di-bosco', '#5C6BC0', '🫐', 0.55, 'Ricchi di antociani e polifenoli, con poche calorie. Colore blu-viola intenso.', 'Sciacquare delicatamente. Alternare con frutta soda per estrarre meglio.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('more', 'More', 'frutti-di-bosco', '#6A1B9A', '🫐', 0.5, 'Antociani, vitamina C e manganese. Sapore intenso e leggermente acidulo.', 'Sciacquare con cura. Colorano molto; abbinare a mela o pera per equilibrio.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('lamponi', 'Lamponi', 'frutti-di-bosco', '#D81B60', '🍓', 0.45, 'Vitamina C, manganese e polifenoli, con dolcezza tenue e nota acidula.', 'Molto delicati: sciacquare appena. Resa contenuta, aggiungono aroma e colore.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('fragole', 'Fragole', 'frutti-di-bosco', '#EF5350', '🍓', 0.55, 'Buona fonte di vitamina C e polifenoli, con dolcezza fresca e poche calorie.', 'Lavare e rimuovere il picciolo. Scegliere fragole ben mature e profumate.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('ribes', 'Ribes', 'frutti-di-bosco', '#B71C1C', '🔴', 0.5, 'Elevata acidità, vitamina C e antociani. Sapore vivace e pungente.', 'Staccare gli acini dai raspi. Usare in piccole dosi per la spiccata acidità.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('carota', 'Carota', 'verdura', '#F39C12', '🥕', 0.5, 'Ricca di beta-carotene, precursore della vitamina A. Dolcezza naturale e colore arancio.', 'Lavare e spuntare le estremità. Non serve sbucciare se ben lavata; ortaggio duro, alternare con morbidi.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('cetriolo', 'Cetriolo', 'verdura', '#66BB6A', '🥒', 0.75, 'Molto idratante e poco calorico, con potassio. Base neutra e rinfrescante.', 'Lavare bene. Buccia ammessa se non cerata; altrimenti sbucciare. Resa molto alta.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('finocchio', 'Finocchio', 'verdura', '#AED581', '🌿', 0.55, 'Note anice-fresche, potassio e poche calorie. Rende il succo aromatico e leggero.', 'Lavare, eliminare la base dura e le parti esterne rovinate. Tagliare a spicchi.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('sedano', 'Sedano', 'verdura', '#9CCC65', '🥬', 0.6, 'Idratante, con potassio e sodio naturale. Sapore erbaceo e salino.', 'Lavare le coste e rimuovere i filamenti più grossi. Ottima resa liquida.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('barbabietola', 'Barbabietola', 'verdura', '#AD1457', '🔴', 0.55, 'Ricca di betalaine e folati, con sapore terroso e dolce. Colore rubino intenso.', 'Lavare e sbucciare. Cruda ha sapore forte: usare in quantità moderate. Macchia molto.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('pomodoro', 'Pomodoro', 'verdura', '#E53935', '🍅', 0.65, 'Fonte di licopene, vitamina C e potassio, con poche calorie. Sapore savory.', 'Lavare e rimuovere il picciolo. Preferire pomodori maturi e sodi.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('spinaci', 'Spinaci', 'verdura', '#388E3C', '🥬', 0.3, 'Apportano folati, vitamina K, magnesio e clorofilla. Sapore delicato.', 'Lavare accuratamente. Foglia tenera: alternare con frutta soda per estrarre il succo.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('cavolo-riccio', 'Cavolo riccio (kale)', 'verdura', '#2E7D32', '🥬', 0.3, 'Ricco di vitamina K, vitamina C, folati e carotenoidi. Sapore vegetale deciso.', 'Lavare e rimuovere la costa centrale più dura. Alternare con mela o cetriolo.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('lattuga', 'Lattuga', 'verdura', '#9CCC65', '🥬', 0.35, 'Molto leggera e idratante, con folati e vitamina K. Sapore neutro-dolce.', 'Lavare le foglie. Resa modesta: usare come componente idratante e delicata.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('zucca', 'Zucca', 'verdura', '#E8871E', '🎃', 0.45, 'Ricca di beta-carotene (provitamina A) e potassio, con sapore dolce e delicato e poche calorie.', 'Sbucciare ed eliminare semi e filamenti. Ortaggio duro: tagliarlo a pezzi piccoli e alternarlo a ingredienti morbidi. Preferire zucca ben matura.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('zenzero', 'Zenzero', 'aromatici', '#E6B84D', '🫚', 0.4, 'Contiene gingeroli e composti aromatici responsabili della tipica piccantezza.', 'Lavare e, se la buccia è spessa, raschiarla. Basta un piccolo pezzo per aromatizzare.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('curcuma', 'Curcuma fresca', 'aromatici', '#E38B29', '🫚', 0.4, 'Radice aromatica ricca di curcuminoidi, dal colore giallo-arancio intenso.', 'Maneggiare con attenzione: colora molto pelle e superfici. Usare in piccole quantità.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('menta', 'Menta', 'aromatici', '#4DB6AC', '🌿', 0.2, 'Foglia aromatica che aggiunge freschezza e note balsamiche, con oli essenziali.', 'Sciacquare. Aggiungere poche foglie per profumare senza coprire gli altri sapori.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('basilico', 'Basilico', 'aromatici', '#66BB6A', '🌿', 0.2, 'Erba aromatica dalle note dolci-speziate, con oli essenziali caratteristici.', 'Sciacquare. Poche foglie sono sufficienti; si abbina bene a pomodoro e frutta estiva.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;
insert into public.ingredients (slug, name, category, color, icon, yield_ratio, contribution, notes) values ('prezzemolo', 'Prezzemolo', 'aromatici', '#43A047', '🌿', 0.25, 'Erba verde ricca di vitamina C, vitamina K e clorofilla, dal sapore intenso.', 'Lavare bene. Usare in piccole quantità: il sapore è deciso e può dominare.')
  on conflict (slug) do update set name=excluded.name, category=excluded.category, color=excluded.color, icon=excluded.icon, yield_ratio=excluded.yield_ratio, contribution=excluded.contribution, notes=excluded.notes;

-- Ricette
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'classico-dorato', 'Classico Dorato', 'Mela · Carota · Zenzero', 'Il grande classico: dolce, agrumato di zenzero e con il colore caldo della carota.', '#F5A623', '#FFE0B2', 230, 54, 46, 3, 2, 0.6, '["vitamina_a","vitamina_c","potassio","polifenoli"]'::jsonb, '["Elevato contenuto di carotenoidi (beta-carotene)","Buona fonte di potassio","Note aromatiche dallo zenzero"]'::jsonb, '["dolce","speziata","ricca-carotenoidi"]'::jsonb, 'Lavare mela e carota; rimuovere il torsolo della mela e spuntare le carote. Raschiare lo zenzero. Alternare carota (soda) e mela per estrarre bene. Non serve sbucciare se ben lavati.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'sole-del-mattino', 'Sole del Mattino', 'Mela · Carota · Limone', 'Fresco e luminoso: la dolcezza di mela e carota ravvivata da un tocco di limone.', '#F6C445', '#FFF0C2', 215, 50, 43, 3, 2, 0.5, '["vitamina_a","vitamina_c","potassio","flavonoidi"]'::jsonb, '["Buona fonte di vitamina C","Elevato contenuto di carotenoidi","Relativamente equilibrata"]'::jsonb, '["fresca","dolce","agrumata","ricca-carotenoidi","ricca-vit-c"]'::jsonb, 'Lavare mela e carota; togliere il torsolo. Sbucciare il limone eliminando la parte bianca amara e non usare la scorza. Alternare gli ingredienti duri e morbidi nell''estrattore.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'verde-fresco', 'Verde Fresco', 'Cetriolo · Finocchio · Mela · Limone', 'Leggero e dissetante, con la nota anice del finocchio e la freschezza del cetriolo.', '#8CBF7A', '#DDEBCF', 150, 34, 27, 3, 2, 0.5, '["vitamina_c","potassio","folati","polifenoli"]'::jsonb, '["Molto idratante e poco calorica","Fonte di potassio","Presenza di vitamina C"]'::jsonb, '["fresca","vegetale","agrumata"]'::jsonb, 'Lavare cetriolo, finocchio e mela. Eliminare la base dura e le parti esterne rovinate del finocchio; togliere il torsolo della mela. Sbucciare il limone. Alternare finocchio e cetriolo con la mela.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'aurora-agrumata', 'Aurora Agrumata', 'Carota · Arancia · Zenzero', 'Solare e vitaminico: arancia e carota con la spinta calda dello zenzero.', '#F39A2B', '#FFDCA8', 195, 44, 36, 3, 3, 0.6, '["vitamina_c","vitamina_a","folati","flavonoidi","potassio"]'::jsonb, '["Buona fonte di vitamina C","Elevato contenuto di carotenoidi","Apporta folati"]'::jsonb, '["fresca","agrumata","speziata","ricca-vit-c","ricca-carotenoidi"]'::jsonb, 'Lavare e spuntare le carote. Sbucciare le arance rimuovendo la parte bianca e non usare la scorza. Raschiare lo zenzero. Alternare carota e arancia nell''estrattore.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'pera-speziata', 'Pera Speziata', 'Mela · Pera · Zenzero', 'Morbido e avvolgente: la dolcezza vellutata della pera con la mela e un accento di zenzero.', '#C9D67E', '#EDF2CE', 255, 62, 52, 3, 1, 0.5, '["potassio","vitamina_c","polifenoli"]'::jsonb, '["Fonte di potassio","Dolce ma con note speziate","Contiene composti polifenolici"]'::jsonb, '["dolce","speziata"]'::jsonb, 'Lavare mela e pera; rimuovere i torsoli. Usare pere mature ma sode per una resa migliore. Raschiare lo zenzero e alternarlo alla frutta.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'anice-e-pera', 'Anice & Pera', 'Finocchio · Pera · Limone', 'Elegante e delicato: la pera addolcisce il finocchio, il limone dà freschezza.', '#B6D08A', '#E4EFD3', 175, 42, 34, 3, 2, 0.5, '["potassio","vitamina_c","folati"]'::jsonb, '["Poco calorica per il volume","Fonte di potassio","Presenza di vitamina C"]'::jsonb, '["fresca","vegetale","agrumata"]'::jsonb, 'Lavare finocchio e pera. Eliminare la base dura del finocchio e il torsolo della pera. Sbucciare il limone. Alternare finocchio e pera nell''estrattore.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'cetriolo-vivo', 'Cetriolo Vivo', 'Cetriolo · Mela · Limone · Zenzero', 'Rinfrescante e vivace, con la nota pungente dello zenzero e il taglio del limone.', '#7CC48A', '#D6EBD9', 165, 38, 31, 3, 2, 0.5, '["vitamina_c","potassio","polifenoli"]'::jsonb, '["Molto idratante","Fonte di vitamina C","Aroma fresco e speziato"]'::jsonb, '["fresca","vegetale","agrumata","speziata"]'::jsonb, 'Lavare cetriolo e mela; togliere il torsolo. Sbucciare il limone. Raschiare lo zenzero. Alternare cetriolo (molto acquoso) e mela per un''estrazione uniforme.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'rubino-terra', 'Rubino Terra', 'Barbabietola · Mela · Carota', 'Terroso e dolce, dal colore rubino profondo: barbabietola bilanciata da mela e carota.', '#B03A6E', '#F0CBDB', 205, 47, 39, 3, 3, 0.5, '["betalaine","folati","vitamina_a","potassio","polifenoli"]'::jsonb, '["Apporta betalaine e folati","Elevato contenuto di carotenoidi","Colore intenso da pigmenti vegetali"]'::jsonb, '["dolce","vegetale","ricca-carotenoidi"]'::jsonb, 'Lavare gli ingredienti; sbucciare la barbabietola e togliere il torsolo della mela. La barbabietola cruda è intensa: dosarla con equilibrio. Attenzione, colora molto le superfici.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'tropicale-verde', 'Tropicale Verde', 'Ananas · Cetriolo · Lime', 'Esotico e dissetante: l''ananas incontra la freschezza di cetriolo e lime.', '#C6B838', '#E9E7B0', 170, 40, 32, 2, 2, 0.4, '["vitamina_c","manganese","potassio"]'::jsonb, '["Buona fonte di vitamina C","Apporta manganese","Idratante e rinfrescante"]'::jsonb, '["fresca","agrumata","ricca-vit-c"]'::jsonb, 'Eliminare buccia e parte centrale fibrosa dell''ananas. Lavare il cetriolo. Sbucciare il lime e usarne poco. Alternare ananas e cetriolo nell''estrattore.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'verde-leggero', 'Verde Leggero', 'Sedano · Cetriolo · Mela', 'Sobrio e depurante nel gusto: erbaceo del sedano, freschezza del cetriolo, un filo di dolcezza.', '#9CCB6A', '#DDECC6', 130, 30, 24, 3, 2, 0.4, '["potassio","vitamina_c","vitamina_k","folati"]'::jsonb, '["Poco calorica","Molto idratante","Fonte di potassio"]'::jsonb, '["fresca","vegetale"]'::jsonb, 'Lavare sedano, cetriolo e mela. Rimuovere i filamenti più grossi del sedano e il torsolo della mela. Alternare le coste di sedano con cetriolo e mela.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'vigna-dorata', 'Vigna Dorata', 'Uva · Mela · Limone', 'Dolce e succosa come un grappolo maturo, con un tocco di limone che asciuga la dolcezza.', '#8E6FB0', '#DED0EB', 270, 66, 60, 2, 1, 0.5, '["potassio","polifenoli","vitamina_c"]'::jsonb, '["Ricca di polifenoli (soprattutto uva nera)","Fonte di potassio","Molto dissetante"]'::jsonb, '["dolce","agrumata"]'::jsonb, 'Staccare gli acini dell''uva dal grappolo e lavarli. Lavare la mela e togliere il torsolo. Sbucciare il limone. Essendo molto dolce, il limone aiuta a bilanciare.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'estate-dolce', 'Estate Dolce', 'Pesca · Mela · Carota', 'Il profumo dell''estate: pesca matura, mela e carota per un sorso morbido e dorato.', '#F0A868', '#FCE0C6', 210, 49, 41, 3, 2, 0.5, '["vitamina_a","vitamina_c","potassio","polifenoli"]'::jsonb, '["Apporta carotenoidi","Fonte di potassio","Aroma dolce e delicato"]'::jsonb, '["dolce","ricca-carotenoidi"]'::jsonb, 'Lavare la frutta e le carote. Rimuovere il nocciolo delle pesche e il torsolo delle mele; spuntare le carote. Preferire pesche mature per una resa migliore.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'bosco-e-frutteto', 'Bosco & Frutteto', 'Mirtilli · Mela · Pera', 'Frutti di bosco e frutteto in un sorso viola intenso, morbido e leggermente acidulo.', '#6A6FB5', '#D2D4EC', 225, 54, 44, 3, 2, 0.6, '["antociani","polifenoli","vitamina_c","manganese"]'::jsonb, '["Ricco di antociani","Fonte di polifenoli","Colore intenso da pigmenti naturali"]'::jsonb, '["dolce","frutti-di-bosco"]'::jsonb, 'Sciacquare delicatamente i mirtilli. Lavare mela e pera e togliere i torsoli. Alternare i mirtilli con la frutta soda per estrarre meglio il succo.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'oro-liquido', 'Oro Liquido', 'Arancia · Carota · Curcuma', 'Colore dorato e nota calda della curcuma fresca, con arancia e carota.', '#EE9A1E', '#FDD9A0', 190, 43, 35, 3, 3, 0.6, '["vitamina_c","vitamina_a","folati","potassio"]'::jsonb, '["Buona fonte di vitamina C","Elevato contenuto di carotenoidi","Nota aromatica dalla curcuma"]'::jsonb, '["agrumata","speziata","ricca-vit-c","ricca-carotenoidi"]'::jsonb, 'Sbucciare le arance eliminando la parte bianca; non usare la scorza. Lavare e spuntare le carote. Maneggiare la curcuma con attenzione: colora molto. Alternare arancia e carota.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'anguria-fresca', 'Anguria Fresca', 'Anguria · Menta · Lime', 'Il sorso più dissetante: anguria idratante, menta balsamica e una punta di lime.', '#EF6B72', '#FBD2D4', 130, 32, 28, 1, 2, 0.4, '["licopene","vitamina_c","potassio"]'::jsonb, '["Molto idratante e poco calorica","Apporta licopene","Rinfrescante"]'::jsonb, '["fresca","dolce","ricca-carotenoidi"]'::jsonb, 'Rimuovere la buccia dell''anguria e tagliarla a pezzi. Sciacquare la menta. Sbucciare il lime. L''anguria è molto acquosa: la resa è alta e il succo molto liquido.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'fragola-fresca', 'Fragola Fresca', 'Fragole · Mela · Limone', 'Dolce e profumato di fragole mature, con mela e un tocco di limone.', '#EC5A5F', '#FAD1D2', 180, 42, 34, 3, 2, 0.5, '["vitamina_c","polifenoli","manganese","potassio"]'::jsonb, '["Buona fonte di vitamina C","Contiene polifenoli","Dolcezza fresca e poche calorie"]'::jsonb, '["fresca","dolce","frutti-di-bosco","ricca-vit-c"]'::jsonb, 'Lavare le fragole e rimuovere il picciolo. Lavare la mela e togliere il torsolo. Sbucciare il limone. Scegliere fragole ben mature per aroma e resa.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'viola-profondo', 'Viola Profondo', 'More · Mirtilli · Mela', 'Intensità di bosco in un sorso viola scuro, ricco e leggermente acidulo.', '#7B3F98', '#DCC7E6', 200, 47, 37, 4, 2, 0.7, '["antociani","polifenoli","vitamina_c","manganese"]'::jsonb, '["Ricco di antociani","Fonte di vitamina C","Elevato apporto di polifenoli"]'::jsonb, '["dolce","frutti-di-bosco","ricca-vit-c"]'::jsonb, 'Sciacquare con cura more e mirtilli. Lavare la mela e togliere il torsolo. Alternare i frutti di bosco alla mela soda per un''estrazione efficace. Colora molto.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'lampone-estivo', 'Lampone Estivo', 'Lamponi · Pesca · Mela', 'Delicato e profumato: lamponi e pesca su una base morbida di mela.', '#D64A78', '#F6CEDD', 195, 45, 36, 4, 2, 0.6, '["vitamina_c","manganese","polifenoli","vitamina_a"]'::jsonb, '["Fonte di vitamina C","Apporta manganese","Aroma delicato e poco calorico"]'::jsonb, '["fresca","dolce","frutti-di-bosco"]'::jsonb, 'Sciacquare appena i lamponi (molto delicati). Rimuovere il nocciolo delle pesche e il torsolo delle mele. Alternare i frutti morbidi con la mela.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'verde-foglia', 'Verde Foglia', 'Spinaci · Mela · Cetriolo · Limone', 'Verde e leggero: gli spinaci resi piacevoli da mela, cetriolo e limone.', '#4E9A4E', '#CDE6CD', 150, 34, 27, 3, 3, 0.6, '["folati","vitamina_k","magnesio","vitamina_c","potassio"]'::jsonb, '["Apporta folati e vitamina K","Fonte di magnesio","Poco calorica e idratante"]'::jsonb, '["fresca","vegetale","ricca-vit-c"]'::jsonb, 'Lavare accuratamente gli spinaci. Lavare mela e cetriolo; togliere il torsolo della mela. Sbucciare il limone. Alternare le foglie tenere con la mela soda per estrarre il succo.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'kale-booster', 'Kale Booster', 'Cavolo riccio · Mela · Limone · Zenzero', 'Verde deciso e tonificante nel gusto: kale bilanciato da mela, limone e zenzero.', '#3C7D3C', '#C6DEC6', 205, 48, 39, 3, 3, 0.6, '["vitamina_k","vitamina_c","folati","vitamina_a","potassio"]'::jsonb, '["Ricca di vitamina K","Buona fonte di vitamina C","Apporta carotenoidi e folati"]'::jsonb, '["vegetale","agrumata","speziata","ricca-vit-c"]'::jsonb, 'Lavare il cavolo riccio e rimuovere la costa centrale più dura. Lavare la mela e togliere il torsolo. Sbucciare il limone; raschiare lo zenzero. Alternare kale e mela.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'rosso-salato', 'Rosso Salato', 'Pomodoro · Sedano · Limone · Basilico', 'Un centrifugato savory: pomodoro maturo, sedano e basilico, con freschezza di limone.', '#D8433B', '#F4C9C6', 110, 22, 17, 3, 3, 0.6, '["licopene","vitamina_c","potassio","vitamina_k"]'::jsonb, '["Apporta licopene","Poco calorica","Fonte di potassio"]'::jsonb, '["fresca","vegetale","ricca-carotenoidi"]'::jsonb, 'Lavare pomodori e sedano; rimuovere il picciolo dei pomodori e i filamenti del sedano. Sbucciare il limone. Aggiungere qualche foglia di basilico sciacquata. Preferire pomodori maturi.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'melograno-rubino', 'Melograno Rubino', 'Melograno · Mela · Barbabietola', 'Colore rubino e sapore agrodolce: melograno e barbabietola addolciti dalla mela.', '#B22A4A', '#F0C6CF', 225, 53, 44, 3, 2, 0.7, '["polifenoli","antociani","betalaine","vitamina_c","folati"]'::jsonb, '["Ricco di polifenoli e antociani","Apporta folati","Colore intenso da pigmenti vegetali"]'::jsonb, '["dolce","vegetale"]'::jsonb, 'Sgranare i melograni usando solo gli arilli. Lavare la mela e togliere il torsolo; sbucciare la barbabietola. Colora molto: attenzione a mani e superfici.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'kiwi-menta', 'Kiwi Menta', 'Kiwi · Mela · Menta', 'Verde e vitaminico: kiwi acidulo, mela dolce e la freschezza della menta.', '#7FB13B', '#DCE9C2', 185, 44, 34, 3, 2, 0.6, '["vitamina_c","vitamina_k","potassio","polifenoli"]'::jsonb, '["Elevato contenuto di vitamina C","Fonte di potassio","Freschezza aromatica"]'::jsonb, '["fresca","ricca-vit-c"]'::jsonb, 'Sbucciare i kiwi. Lavare la mela e togliere il torsolo. Sciacquare la menta e usarne poche foglie. Non eccedere col kiwi per evitare note amare dai semini.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'melone-sole', 'Melone Sole', 'Melone · Arancia', 'Dolce e aromatico: melone maturo e arancia, un sorso morbido e solare.', '#F2A65A', '#FCDFC0', 175, 41, 36, 2, 3, 0.5, '["vitamina_a","vitamina_c","folati","potassio"]'::jsonb, '["Apporta beta-carotene","Buona fonte di vitamina C","Idratante"]'::jsonb, '["dolce","agrumata","ricca-vit-c","ricca-carotenoidi"]'::jsonb, 'Rimuovere buccia e semi del melone. Sbucciare le arance eliminando la parte bianca; non usare la scorza. Preferire un melone maturo e profumato.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'finocchio-pera-menta', 'Finocchio, Pera & Menta', 'Finocchio · Pera · Menta', 'Fresco e balsamico: finocchio e pera con la nota pulita della menta.', '#A9CC8A', '#E0EDD1', 170, 41, 33, 3, 2, 0.5, '["potassio","vitamina_c","folati"]'::jsonb, '["Poco calorica per il volume","Fonte di potassio","Freschezza aromatica"]'::jsonb, '["fresca","vegetale"]'::jsonb, 'Lavare finocchio e pera. Eliminare la base dura del finocchio e il torsolo della pera. Sciacquare la menta. Alternare finocchio e pera nell''estrattore.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'sole-speziato', 'Sole Speziato', 'Carota · Mela · Curcuma · Limone', 'Caldo e agrumato: carota e mela con curcuma e un tocco di limone.', '#EFA92B', '#FBDFA6', 185, 43, 35, 3, 2, 0.6, '["vitamina_a","vitamina_c","potassio","polifenoli"]'::jsonb, '["Elevato contenuto di carotenoidi","Fonte di vitamina C","Nota aromatica dalla curcuma"]'::jsonb, '["dolce","speziata","agrumata","ricca-carotenoidi"]'::jsonb, 'Lavare e spuntare le carote; lavare la mela e togliere il torsolo. Maneggiare la curcuma con attenzione. Sbucciare il limone. Alternare carota e mela.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'tropicale-speziato', 'Tropicale Speziato', 'Ananas · Arancia · Zenzero', 'Solare e vivace: ananas e arancia con la spinta calda dello zenzero.', '#F0B429', '#FCE6A6', 205, 48, 40, 2, 2, 0.5, '["vitamina_c","manganese","folati","potassio"]'::jsonb, '["Buona fonte di vitamina C","Apporta manganese","Aroma tropicale e speziato"]'::jsonb, '["agrumata","speziata","dolce","ricca-vit-c"]'::jsonb, 'Eliminare buccia e parte centrale fibrosa dell''ananas. Sbucciare le arance eliminando la parte bianca. Raschiare lo zenzero. Alternare ananas e arancia.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'verde-erbaceo', 'Verde Erbaceo', 'Cetriolo · Sedano · Prezzemolo · Limone · Mela', 'Verde e minerale: cetriolo e sedano con prezzemolo, ammorbiditi da mela e limone.', '#5EA55E', '#D2E8D2', 130, 29, 22, 3, 3, 0.6, '["vitamina_c","vitamina_k","folati","potassio","magnesio"]'::jsonb, '["Poco calorica","Fonte di vitamina C e vitamina K","Molto idratante"]'::jsonb, '["fresca","vegetale","ricca-vit-c"]'::jsonb, 'Lavare cetriolo, sedano, prezzemolo e mela. Rimuovere i filamenti del sedano e il torsolo della mela. Usare poco prezzemolo (sapore deciso). Sbucciare il limone.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'frutteto-viola', 'Frutteto Viola', 'Prugna · Mela · Uva', 'Pieno e succoso: prugne mature, mela e uva per un sorso dolce e profondo.', '#8A5A8A', '#DECBDE', 250, 60, 51, 3, 1, 0.5, '["potassio","polifenoli","antociani","vitamina_c"]'::jsonb, '["Ricco di polifenoli","Fonte di potassio","Colore intenso da pigmenti naturali"]'::jsonb, '["dolce"]'::jsonb, 'Lavare la frutta. Rimuovere il nocciolo delle prugne e il torsolo delle mele; staccare gli acini dell''uva. Alternare frutta morbida e soda per un''estrazione uniforme.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'agrumi-e-carota', 'Agrumi & Carota', 'Pompelmo · Arancia · Carota', 'Vivace e leggermente amarognolo: pompelmo e arancia bilanciati dalla dolcezza della carota.', '#F07E7A', '#FBD5CF', 175, 40, 32, 3, 3, 0.5, '["vitamina_c","vitamina_a","flavonoidi","folati","potassio"]'::jsonb, '["Elevata fonte di vitamina C","Apporta carotenoidi","Contiene flavonoidi"]'::jsonb, '["fresca","agrumata","ricca-vit-c","ricca-carotenoidi"]'::jsonb, 'Sbucciare pompelmo e arance rimuovendo albedo e membrane; non usare la scorza. Lavare e spuntare le carote. Nota: il pompelmo può interagire con alcuni farmaci.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'terra-e-sole', 'Terra & Sole', 'Barbabietola · Arancia · Zenzero', 'Terroso e agrumato: barbabietola e arancia con l''accento vivace dello zenzero.', '#B23A5B', '#F0C8D2', 205, 47, 39, 3, 3, 0.5, '["betalaine","vitamina_c","folati","potassio"]'::jsonb, '["Apporta betalaine e folati","Buona fonte di vitamina C","Colore rubino intenso"]'::jsonb, '["agrumata","vegetale","speziata","ricca-vit-c"]'::jsonb, 'Lavare e sbucciare la barbabietola. Sbucciare le arance eliminando la parte bianca. Raschiare lo zenzero. La barbabietola cruda è intensa: dosarla con equilibrio.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'mandarino-dolce', 'Mandarino Dolce', 'Mandarino · Carota · Mela', 'Dolce e avvolgente: mandarino profumato con carota e mela.', '#F0913A', '#FBDDBB', 205, 48, 40, 3, 2, 0.5, '["vitamina_c","vitamina_a","flavonoidi","potassio"]'::jsonb, '["Fonte di vitamina C","Elevato contenuto di carotenoidi","Dolcezza naturale"]'::jsonb, '["dolce","agrumata","ricca-carotenoidi","ricca-vit-c"]'::jsonb, 'Sbucciare i mandarini ed eliminare eventuali semi; non usare la scorza. Lavare e spuntare le carote; lavare la mela e togliere il torsolo. Alternare gli ingredienti.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'ribes-vivace', 'Ribes Vivace', 'Ribes · Mela · Pera', 'Vivace e agrodolce: ribes pungente ammorbidito da mela e pera.', '#B02231', '#F0C4C9', 195, 46, 37, 3, 2, 0.5, '["vitamina_c","antociani","polifenoli","potassio"]'::jsonb, '["Elevata fonte di vitamina C","Ricco di antociani","Sapore vivace"]'::jsonb, '["fresca","frutti-di-bosco","ricca-vit-c"]'::jsonb, 'Staccare gli acini di ribes dai raspi e sciacquarli. Lavare mela e pera e togliere i torsoli. Il ribes è molto acido: la frutta dolce bilancia il sorso.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'duetto-di-pesche', 'Duetto di Pesche', 'Nettarina · Pesca · Mela', 'Estivo e morbido: nettarina e pesca su una base di mela, dolce e profumato.', '#EF9E68', '#FBDCC4', 210, 50, 42, 3, 2, 0.5, '["vitamina_c","vitamina_a","potassio","polifenoli"]'::jsonb, '["Apporta carotenoidi","Fonte di potassio","Aroma dolce e delicato"]'::jsonb, '["dolce"]'::jsonb, 'Lavare la frutta. Rimuovere il nocciolo di nettarine e pesche e il torsolo delle mele. La buccia liscia della nettarina può essere lasciata dopo lavaggio.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'estate-rossa', 'Estate Rossa', 'Fragole · Anguria · Menta', 'Il sorso più estivo: fragole e anguria idratante con un soffio di menta.', '#EE5865', '#FAD0D4', 150, 35, 30, 2, 2, 0.5, '["vitamina_c","licopene","potassio","polifenoli"]'::jsonb, '["Buona fonte di vitamina C","Molto idratante e poco calorica","Apporta licopene"]'::jsonb, '["fresca","dolce","frutti-di-bosco","ricca-vit-c"]'::jsonb, 'Lavare le fragole e rimuovere il picciolo. Togliere la buccia dell''anguria e tagliarla a pezzi. Sciacquare la menta. Molto acquosa: resa alta e succo leggero.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'autunno-dorato', 'Autunno Dorato', 'Zucca · Carota · Mela · Zenzero', 'Caldo e dolce come l''autunno: zucca e carota con la mela e un accento di zenzero.', '#E8871E', '#FBDBA8', 195, 45, 36, 3, 3, 0.6, '["vitamina_a","vitamina_c","potassio","polifenoli"]'::jsonb, '["Elevato contenuto di carotenoidi (beta-carotene)","Fonte di potassio","Nota aromatica dallo zenzero"]'::jsonb, '["dolce","vegetale","speziata","ricca-carotenoidi"]'::jsonb, 'Lavare gli ingredienti. Sbucciare la zucca ed eliminare semi e filamenti; togliere il torsolo della mela e spuntare le carote. La zucca è dura: tagliarla a pezzi piccoli e alternarla alla mela. Raschiare lo zenzero.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'zucca-e-arancia', 'Zucca & Arancia', 'Zucca · Arancia · Curcuma', 'Solare e vellutato: la dolcezza della zucca incontra l''arancia e la nota calda della curcuma.', '#EE9A2E', '#FCE0B0', 185, 41, 33, 3, 3, 0.5, '["vitamina_a","vitamina_c","folati","potassio"]'::jsonb, '["Buona fonte di vitamina C","Elevato contenuto di carotenoidi","Nota aromatica dalla curcuma"]'::jsonb, '["agrumata","vegetale","speziata","ricca-vit-c","ricca-carotenoidi"]'::jsonb, 'Sbucciare la zucca ed eliminare semi e filamenti; tagliarla a pezzi piccoli. Sbucciare le arance rimuovendo la parte bianca; non usare la scorza. Maneggiare la curcuma con attenzione: colora molto. Alternare zucca e arancia.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;
insert into public.recipes (slug, name, subtitle, description, color_primary, color_secondary, kcal, carbs, sugars, fiber, protein, fat, micronutrients, benefits, tags, preparation) values (
  'vellutato-autunno', 'Vellutato d''Autunno', 'Zucca · Mela · Carota · Limone', 'Morbido e avvolgente: zucca e carota addolcite dalla mela, con un tocco di limone.', '#E0912A', '#F7D9A6', 200, 47, 38, 3, 2, 0.5, '["vitamina_a","vitamina_c","potassio","polifenoli"]'::jsonb, '["Elevato contenuto di carotenoidi","Fonte di vitamina C","Sapore dolce e delicato"]'::jsonb, '["dolce","vegetale","ricca-carotenoidi"]'::jsonb, 'Lavare gli ingredienti. Sbucciare la zucca ed eliminare semi e filamenti; togliere il torsolo della mela e spuntare le carote. Sbucciare il limone. La zucca è dura: tagliarla a pezzi piccoli e alternarla alla mela.'
) on conflict (slug) do update set name=excluded.name, subtitle=excluded.subtitle, description=excluded.description, color_primary=excluded.color_primary, color_secondary=excluded.color_secondary, kcal=excluded.kcal, carbs=excluded.carbs, sugars=excluded.sugars, fiber=excluded.fiber, protein=excluded.protein, fat=excluded.fat, micronutrients=excluded.micronutrients, benefits=excluded.benefits, tags=excluded.tags, preparation=excluded.preparation;

-- Collegamento ricette <-> ingredienti
delete from public.recipe_ingredients;
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('classico-dorato', 'mela', 500, '~3 mele', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('classico-dorato', 'carota', 500, '~6 carote', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('classico-dorato', 'zenzero', 18, '1 pezzetto (~2 cm)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('sole-del-mattino', 'mela', 500, '~3 mele', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('sole-del-mattino', 'carota', 480, '~6 carote', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('sole-del-mattino', 'limone', 60, '~½ limone (succo)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-fresco', 'cetriolo', 300, '~1 cetriolo', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-fresco', 'finocchio', 250, '~1 finocchio', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-fresco', 'mela', 340, '~2 mele', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-fresco', 'limone', 50, '~½ limone (succo)', 3);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('aurora-agrumata', 'carota', 600, '~7 carote', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('aurora-agrumata', 'arancia', 580, '~4 arance', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('aurora-agrumata', 'zenzero', 15, '1 pezzetto (~2 cm)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('pera-speziata', 'mela', 450, '~3 mele', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('pera-speziata', 'pera', 500, '~3 pere', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('pera-speziata', 'zenzero', 12, '1 pezzetto (~1,5 cm)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('anice-e-pera', 'finocchio', 400, '~1 finocchio grande', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('anice-e-pera', 'pera', 600, '~3-4 pere', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('anice-e-pera', 'limone', 50, '~½ limone (succo)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('cetriolo-vivo', 'cetriolo', 400, '~1 cetriolo grande', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('cetriolo-vivo', 'mela', 450, '~3 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('cetriolo-vivo', 'limone', 55, '~½ limone (succo)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('cetriolo-vivo', 'zenzero', 12, '1 pezzetto (~1,5 cm)', 3);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('rubino-terra', 'barbabietola', 250, '~1 barbabietola piccola', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('rubino-terra', 'mela', 450, '~3 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('rubino-terra', 'carota', 350, '~4 carote', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('tropicale-verde', 'ananas', 450, '~½ ananas', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('tropicale-verde', 'cetriolo', 350, '~1 cetriolo', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('tropicale-verde', 'lime', 40, '~1 lime (succo)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-leggero', 'sedano', 260, '~3-4 coste', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-leggero', 'cetriolo', 300, '~1 cetriolo', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-leggero', 'mela', 340, '~2 mele', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('vigna-dorata', 'uva', 450, '~1 grappolo medio', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('vigna-dorata', 'mela', 400, '~2-3 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('vigna-dorata', 'limone', 50, '~½ limone (succo)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('estate-dolce', 'pesca', 400, '~3 pesche', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('estate-dolce', 'mela', 400, '~2-3 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('estate-dolce', 'carota', 350, '~4 carote', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('bosco-e-frutteto', 'mirtilli', 250, '~2 tazze', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('bosco-e-frutteto', 'mela', 450, '~3 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('bosco-e-frutteto', 'pera', 350, '~2 pere', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('oro-liquido', 'arancia', 560, '~4 arance', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('oro-liquido', 'carota', 620, '~7 carote', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('oro-liquido', 'curcuma', 12, '1 pezzetto (~1,5 cm)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('anguria-fresca', 'anguria', 750, '~2 fette grandi', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('anguria-fresca', 'menta', 6, '~6 foglie', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('anguria-fresca', 'lime', 40, '~1 lime (succo)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('fragola-fresca', 'fragole', 400, '~2-3 tazze', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('fragola-fresca', 'mela', 560, '~3-4 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('fragola-fresca', 'limone', 45, '~½ limone (succo)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('viola-profondo', 'more', 250, '~2 tazze', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('viola-profondo', 'mirtilli', 200, '~1½ tazza', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('viola-profondo', 'mela', 450, '~3 mele', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('lampone-estivo', 'lamponi', 220, '~1½ tazza', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('lampone-estivo', 'pesca', 400, '~3 pesche', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('lampone-estivo', 'mela', 400, '~2-3 mele', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-foglia', 'spinaci', 120, '~3 manciate', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-foglia', 'mela', 450, '~3 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-foglia', 'cetriolo', 350, '~1 cetriolo', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-foglia', 'limone', 50, '~½ limone (succo)', 3);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('kale-booster', 'cavolo-riccio', 170, '~6 foglie', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('kale-booster', 'mela', 780, '~5 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('kale-booster', 'limone', 55, '~½ limone (succo)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('kale-booster', 'zenzero', 12, '1 pezzetto (~1,5 cm)', 3);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('rosso-salato', 'pomodoro', 600, '~5 pomodori', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('rosso-salato', 'sedano', 300, '~4 coste', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('rosso-salato', 'limone', 45, '~½ limone (succo)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('rosso-salato', 'basilico', 5, '~5 foglie', 3);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('melograno-rubino', 'melograno', 300, '~2 melograni (arilli)', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('melograno-rubino', 'mela', 450, '~3 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('melograno-rubino', 'barbabietola', 180, '~1 barbabietola piccola', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('kiwi-menta', 'kiwi', 380, '~4 kiwi', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('kiwi-menta', 'mela', 600, '~4 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('kiwi-menta', 'menta', 5, '~5 foglie', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('melone-sole', 'melone', 650, '~½ melone grande', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('melone-sole', 'arancia', 420, '~3 arance', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('finocchio-pera-menta', 'finocchio', 420, '~1 finocchio grande', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('finocchio-pera-menta', 'pera', 600, '~3-4 pere', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('finocchio-pera-menta', 'menta', 5, '~5 foglie', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('sole-speziato', 'carota', 530, '~6 carote', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('sole-speziato', 'mela', 470, '~3 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('sole-speziato', 'curcuma', 12, '1 pezzetto (~1,5 cm)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('sole-speziato', 'limone', 50, '~½ limone (succo)', 3);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('tropicale-speziato', 'ananas', 600, '~⅔ ananas', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('tropicale-speziato', 'arancia', 530, '~4 arance', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('tropicale-speziato', 'zenzero', 15, '1 pezzetto (~2 cm)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-erbaceo', 'cetriolo', 350, '~1 cetriolo', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-erbaceo', 'sedano', 200, '~3 coste', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-erbaceo', 'prezzemolo', 15, '~1 ciuffo', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-erbaceo', 'limone', 50, '~½ limone (succo)', 3);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('verde-erbaceo', 'mela', 350, '~2 mele', 4);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('frutteto-viola', 'prugna', 350, '~5 prugne', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('frutteto-viola', 'mela', 400, '~2-3 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('frutteto-viola', 'uva', 300, '~1 grappolo piccolo', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('agrumi-e-carota', 'pompelmo', 350, '~1 pompelmo', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('agrumi-e-carota', 'arancia', 350, '~2-3 arance', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('agrumi-e-carota', 'carota', 350, '~4 carote', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('terra-e-sole', 'barbabietola', 350, '~1-2 barbabietole', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('terra-e-sole', 'arancia', 750, '~5 arance', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('terra-e-sole', 'zenzero', 12, '1 pezzetto (~1,5 cm)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('mandarino-dolce', 'mandarino', 400, '~5 mandarini', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('mandarino-dolce', 'carota', 400, '~5 carote', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('mandarino-dolce', 'mela', 350, '~2 mele', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('ribes-vivace', 'ribes', 200, '~1½ tazza', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('ribes-vivace', 'mela', 450, '~3 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('ribes-vivace', 'pera', 350, '~2 pere', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('duetto-di-pesche', 'nettarina', 400, '~3 nettarine', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('duetto-di-pesche', 'pesca', 350, '~2-3 pesche', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('duetto-di-pesche', 'mela', 350, '~2 mele', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('estate-rossa', 'fragole', 300, '~2 tazze', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('estate-rossa', 'anguria', 550, '~1-2 fette grandi', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('estate-rossa', 'menta', 5, '~5 foglie', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('autunno-dorato', 'zucca', 350, '~1 fetta grande', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('autunno-dorato', 'carota', 400, '~5 carote', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('autunno-dorato', 'mela', 400, '~2-3 mele', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('autunno-dorato', 'zenzero', 12, '1 pezzetto (~1,5 cm)', 3);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('zucca-e-arancia', 'zucca', 450, '~1 fetta grande', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('zucca-e-arancia', 'arancia', 700, '~5 arance', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('zucca-e-arancia', 'curcuma', 12, '1 pezzetto (~1,5 cm)', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('vellutato-autunno', 'zucca', 350, '~1 fetta grande', 0);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('vellutato-autunno', 'mela', 450, '~3 mele', 1);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('vellutato-autunno', 'carota', 250, '~3 carote', 2);
insert into public.recipe_ingredients (recipe_slug, ingredient_slug, grams, qty, sort_order) values ('vellutato-autunno', 'limone', 40, '~½ limone (succo)', 3);

